services:
  postgres:
    image: postgres:15
    container_name: problem-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: problem_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres-data: