version: '4'
services:
  mongodb:
    image: mongo
    container_name: submission-db
    environment:
      MONGO_INITDB_DATABASE: submission-service
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - submission-data:/data/db
    networks:
      - backend

volumes:
    submission-data:

networks:
    backend:
        driver: bridge