spring:
  application:
    name: submission-service

  data:
    mongodb:
      host: ${SUBMISSION_DB_HOST:localhost}
      port: ${SUBMISSION_DB_PORT:27017}
      database: submission-service
      username: ${SUBMISSION_DB_USERNAME:mongodb}
      password: ${SUBMISSION_DB_PASSWORD:password}
      authentication-database: admin

problem-service:
  url: ${PROBLEM_SERVICE_URL:http://localhost:8080}

server:
  port: ${SUBMISSION_SERVER_PORT:8082}