spring:
  application:
    name: submission-service

  #  security:
  #    oauth2:
  #      client:
  #        registration:
  #          submission-service:
  #            provider: submission-service
  #            client-id: submission-service
  #            client-secret: e6MnTijxlStyQqVvIj0idMaUz0NYNoe6
  #            authorization-grant-type: client_credentials
  #            scope: openid+profile+email
  #
  
  data:
    mongodb:
      host: ${SUBMISSION_DB_HOST:localhost}
      port: ${SUBMISSION_DB_PORT:27017}
      database: submission-service
      username: ${SUBMISSION_DB_USERNAME:mongodb}
      password: ${SUBMISSION_DB_PASSWORD:password}
      authentication-database: admin

  kafka:
    bootstrap-servers=: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    template.default-topic: problem-submission
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    properties:
#      spring.json.add.type.headers: false
#      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
#      properties.schema.registry.url: http://localhost:28081

problem-service:
  url: ${PROBLEM_SERVICE_URL:http://localhost:8080}

resilience4j:
  circuitbreaker.instances.problem-service:
    failureRateThreshold: 50
    waitDurationInOpenState: 5s
    permittedNumberOfCallsInHalfOpenState: 3
    minimumNumberOfCalls: 5
    slidingWindowSize: 10
    slidingWindowType: COUNT_BASED
    automaticTransitionFromOpenToHalfOpenEnabled: true
    registerHealthIndicator: true
  timelimiter.instances.problem-service:
    timeoutDuration: 5s
  retry.instances.problem-service:
    maxAttempts: 3
    waitDuration: 2s

# Keycloak Configuration
#keycloak:
#  auth-server-url: ${OAUTH2_SERVER_URL:http://localhost:9191/realms/codebox/protocol/openid-connect/auth}
#  redirect-uri: ${OAUTH2_REDIRECT_URL:http://localhost:9010/login/oauth2/code/keycloak}
#  token-uri: ${OAUTH2_SERVER_URL:http://localhost:9191/realms/codebox/protocol/openid-connect/token}
#  certificate-uri: ${OAUTH2_SERVER_URL:http://localhost:9191/realms/codebox/protocol/openid-connect/certs}
#  scope: openid+profile+email
#  client:
#    id: api-gateway
#    secret: t8Qd0iZg0i6oQQIwDYg4Ycrd6TrmMHKu

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: ${SUBMISSION_SERVER_PORT:8082}
#
#logging:
#  level:
#    org.springframework: DEBUG