spring:
  application:
    name: product-service

  datasource:
    url: ${PROBLEM_DB_URL:jdbc:postgresql://localhost:5432/problem_db}
    username: ${PROBLEM_DB_USERNAME:postgres}
    password: ${PROBLEM_DB_PASSWORD:root}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: ${PROBLEM_SERVER_PORT:8080}

# Keycloak Configuration
#keycloak:
#  auth-server-url: ${OAUTH2_SERVER_URL:http://localhost:9191/realms/codebox/protocol/openid-connect/auth}
#  redirect-uri: ${OAUTH2_REDIRECT_URL:http://localhost:9010/login/oauth2/code/keycloak}
#  token-uri: ${OAUTH2_SERVER_URL:http://localhost:9191/realms/codebox/protocol/openid-connect/token}
#  certificate-uri: ${OAUTH2_SERVER_URL:http://localhost:9191/realms/codebox/protocol/openid-connect/certs}
#  scope: openid+profile+email
#  client:
#    id: api-gateway
#    secret: t8Qd0iZg0i6oQQIwDYg4Ycrd6TrmMHKu

#logging.level.org.springframework.web: DEBUG
#logging.level.org.springframework.boot: DEBUG