version: "4"
name: "Codebox"
services: #  keycloak:
  #    image: quay.io/keycloak/keycloak:26.1.0
  #    command: [ 'start-dev','--http-port=9191','--import-realm' ]
  #    volumes:
  #      - ./realm-config:/opt/keycloak/data/import
  #    container_name: keycloak
  #    hostname: keycloak
  #    environment:
  #      - KEYCLOAK_ADMIN=admin
  #      - KEYCLOAK_ADMIN_PASSWORD=admin1234
  #    ports:
  #      - "9191:9191"
  #    deploy:
  #      resources:
  #        limits:
  #          memory: 512M

  problem-catalog-db:
    image: postgres:15
    container_name: problem-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: problem_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - problem-catalog-data:/var/lib/postgresql/data

  submission-db:
    image: mongo
    container_name: submission-db
    environment:
      MONGO_INITDB_DATABASE: submission-service
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - submission-data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "29092:29092"
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "28080:8080"
    depends_on:
      - kafka
      - schema-registry
    environment:
      KAFKA_CLUSTERS_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "28081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081

volumes:
  problem-catalog-data:
  submission-data:
